name: Terraform Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # Levantamos LocalStack manualmente usando Docker para evitar errores de "Action not found"
      - name: Iniciar LocalStack (v4.14.0)
        run: |
          docker run -d \
            --name localstack_main \
            -p 4566:4566 \
            -e SERVICES=s3,dynamodb \
            -e DEBUG=1 \
            localstack/localstack:4.14.0
          
          # Esperar a que LocalStack esté listo
          timeout 60s bash -c "until curl -s localhost:4566/_localstack/health | grep -q '\"s3\": \"running\"'; do sleep 2; done"
          echo "LocalStack está listo para recibir comandos"

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
